name: Daily Python Script

on:
  schedule:
    # Runs daily at 12:00 UTC (7:00 AM EST)
    - cron: "0 12 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Specify your Python version

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run your Python script
      - name: Run script
        run: python main.py
