name: Daily Python Script

on:
  schedule:
    # Runs daily at 12:00 UTC (7:00 AM EST)
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Added to ensure full git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'  # Added pip caching for faster installations

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install spotipy

      - name: Run script
        env:  # Add this if you need environment variables
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: python data_collection.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update data files"
          git push

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: script-output
          path: |
            data/
            *.json
            *.csv
          retention-days: 7
